server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  # 添加路由前缀
  prefix: /api
  routes:
    # 将商品服务映射到 /item/**
    item-service: /item/**
    upload-service: /upload/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
  # 覆盖敏感头信息过滤，什么都不写 => 不过滤
  sensitive-headers:
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 熔断超时时长：6000 ms
            timeoutInMilliseconds: 6000
ribbon:
  # ribbon 链接超时时长
  ConnectTimeout: 500
  # ribbon 读取超时时长
  ReadTimeout: 2000
  # 当前服务重试次数
  MaxAutoRetries: 0
  # 切换服务重试次数
  MaxAutoRetriesNextServer: 1
  # 是否对所有的请求方式都重试，只对 get 请求重试
  OkToRetryOnAllOperations: false


# 跨域请求配置
ly:
  cors:
    # 允许的域
    allowedOrigins:
      - http://manage.leyou.com
      - http://www.leyou.com
      # 开发阶段，方便测试，添加 localhost
      - http://localhost:9001
      - http://127.0.0.1:9001
      - http://localhost:9002
      - http://127.0.0.1:9002
    # 是否发送 cookie 信息
    allowCredentials: true
    # 头信息
    allowedHeaders:
      - "*"
    # 允许的请求方式
    allowedMethods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
      - HEAD
    # 有效时长，单位是秒
    maxAge: 3600
    # 拦截路径
    filterPath: "/**"